import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    "./index.html",
    "./src/**/*.{ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "#dadada",
        "surface-container-low": "#f3f3f4",
        "on-tertiary-fixed": "#ffffff",
        "outline": "#777777",
        "on-background": "#1a1c1c",
        "tertiary-fixed-dim": "#474747",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e2e2e2",
        "outline-variant": "#c6c6c6",
        "on-secondary-container": "#1b1b1b",
        "surface": "#f9f9f9",
        "on-error-container": "#410002",
        "on-surface-variant": "#474747",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#3b3b3b",
        "on-tertiary-container": "#ffffff",
        "secondary": "#5e5e5e",
        "error-container": "#ffdad6",
        "surface-container": "#eeeeee",
        "surface-tint": "#5e5e5e",
        "inverse-primary": "#c6c6c6",
        "background": "#f9f9f9",
        "primary-container": "#3b3b3b",
        "primary": "#000000",
        "on-error": "#ffffff",
        "primary-fixed": "#5e5e5e",
        "primary-fixed-dim": "#474747",
        "surface-bright": "#f9f9f9",
        "on-tertiary": "#e2e2e2",
        "on-secondary-fixed": "#1b1b1b",
        "inverse-surface": "#2f3131",
        "tertiary": "#3b3b3b",
        "error": "#ba1a1a",
        "secondary-fixed": "#c6c6c6",
        "secondary-container": "#d4d4d4",
        "on-surface": "#1a1c1c",
        "surface-container-highest": "#e2e2e2",
        "on-tertiary-fixed-variant": "#e2e2e2",
        "on-primary-fixed-variant": "#e2e2e2",
        "on-primary": "#e2e2e2",
        "surface-container-high": "#e8e8e8",
        "inverse-on-surface": "#f0f1f1",
        "tertiary-fixed": "#5e5e5e",
        "on-primary-container": "#ffffff",
        "on-primary-fixed": "#ffffff",
        "tertiary-container": "#747474",
        "secondary-fixed-dim": "#ababab",
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0px",
        "lg": "0px",
        "xl": "0px",
        "full": "9999px",
      },
    },
  },
  plugins: [],
}

export default config
